%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-rostime
Version:        0.7.1
Release:        1%{?dist}
Summary:        ROS rostime package

License:        BSD
URL:            http://ros.org/wiki/rostime
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-date-time
Requires:       boost-system
Requires:       boost-thread
Requires:       ros-noetic-cpp-common
BuildRequires:  boost-date-time
BuildRequires:  boost-system
BuildRequires:  boost-thread
BuildRequires:  ros-noetic-catkin >= 0.5.68
BuildRequires:  ros-noetic-cpp-common

%description
Time and Duration implementations for C++ libraries, including roscpp.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Sat Jan 25 2020 Dirk Thomas <dthomas@osrfoundation.org> - 0.7.1-1
- Autogenerated by Bloom

* Fri Jan 24 2020 Dirk Thomas <dthomas@osrfoundation.org> - 0.7.0-1
- Autogenerated by Bloom

